/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import jdbc.DatabaseQueryService;

import java.io.IOException;

public class App {
    public static void main(String[] args) throws IOException {
        DatabaseQueryService databaseQueryService = new DatabaseQueryService();

        for (Object o:databaseQueryService.printProjectPrices()) {
            System.out.println(o);
        }
        System.out.println();

        for (Object o:databaseQueryService.findMaxSalaryWorker()) {
            System.out.println(o);
        }
        System.out.println();

        for (Object o:databaseQueryService.findYoungestEldestWorkers()) {
            System.out.println(o);
        }
        System.out.println();

        for (Object o:databaseQueryService.findLongestProject()) {
            System.out.println(o);
        }
        System.out.println();

        for (Object o:databaseQueryService.findMaxProjectsClient()) {
            System.out.println(o);
        }
        System.out.println();
    }
}
